export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE'

export const HIDE_SEC_HEADER_COMPONENTS = 'HIDE_SEC_HEADER_COMPONENTS'
export const FILTER_COMMITS = 'FILTER_COMMITS'

export const SAVE_REPOS = 'SAVE_REPOS'

export const SAVE_COMMITS = 'SAVE_COMMITS'

export const UPDATE_SELECTED_REPO = 'UPDATE_SELECTED_REPO'